import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { 
  Search, Shield, Database, Zap, ArrowRight, Check, Activity, 
  Globe, User, Car, CreditCard, ShieldCheck, HelpCircle 
} from 'lucide-react';
import { Link } from 'react-router-dom';
import Navbar from '../components/layout/Navbar';
import Footer from '../components/layout/Footer';

export default function Landing() {
  return (
    <div className="min-h-screen bg-[#030102] text-gray-200 selection:bg-pink-500/30 selection:text-white relative overflow-hidden font-sans">
      
      {/* --- MOONWITCH ATMOSPHERIC BACKGROUND (ENHANCED INTENSITY) --- */}
      
      {/* 1. The "Moon" Glow (Top Right) - Brighter & Wider */}
      <div className="absolute top-[-10%] right-[-5%] w-[700px] h-[700px] bg-white/10 blur-[100px] rounded-full pointer-events-none mix-blend-screen" />
      
      {/* 2. The "Floral Ground" Glow (Absolute Bottom) - Richer Crimson/Rose */}
      <div className="absolute bottom-0 inset-x-0 h-[800px] bg-gradient-to-t from-rose-700/30 via-pink-900/15 to-transparent pointer-events-none mix-blend-screen" />
      
      {/* 3. Deep Ambient Center Glow - More visible */}
      <div className="absolute top-[20%] left-1/2 -translate-x-1/2 w-[900px] h-[600px] bg-pink-600/15 blur-[120px] rounded-full pointer-events-none mix-blend-screen" />
      
      {/* 4. Cinematic Noise Overlay */}
      <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-[0.04] pointer-events-none mix-blend-overlay z-0" />

      {/* 5. Floating Pink Leaves / Petals (Increased Density & Glow) */}
      <FloatingPetals />

      <Navbar />

      {/* 1. HERO SECTION */}
      <section className="relative pt-40 pb-20 px-6 max-w-7xl mx-auto text-center flex flex-col items-center z-10">
        <motion.div initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, ease: "easeOut" }} className="w-full">
          
          <div className="mx-auto w-fit px-4 py-1.5 rounded-full border border-pink-500/30 bg-pink-500/[0.05] text-pink-300 text-xs font-medium tracking-wide mb-8 backdrop-blur-md flex items-center gap-2 shadow-[0_0_20px_rgba(236,72,153,0.2)]">
            <span className="w-2 h-2 rounded-full bg-pink-500 animate-pulse shadow-[0_0_10px_rgba(236,72,153,0.9)]" />
            MoonWitch OSINT Engine v4.2
          </div>
          
          <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight mb-6 max-w-4xl mx-auto leading-[1.1] text-white h-[120px] md:h-[160px]">
            Intelligence <br />
            <TypewriterEffect words={['Beyond Search.', 'In Real-Time.', 'Without Limits.', 'At Scale.']} />
          </h1>
          
          <p className="text-gray-400 text-lg max-w-2xl mx-auto mb-10 leading-relaxed mt-4 drop-shadow-md">
            An enterprise-grade intelligence platform. Recover information from public databases instantly, verify identities, and evaluate risk footprints securely.
          </p>
          
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 relative z-20">
            <Link to="/login" className="px-8 py-3.5 bg-white text-black hover:bg-pink-100 rounded-full font-semibold inline-flex items-center gap-2 transition-colors shadow-[0_0_25px_rgba(255,255,255,0.3)] hover:shadow-[0_0_40px_rgba(236,72,153,0.5)]">
              Start Analysis <ArrowRight className="w-4 h-4" />
            </Link>
            <a href="#pricing" className="px-8 py-3.5 bg-black/50 backdrop-blur-md border border-white/20 hover:border-pink-500/60 hover:bg-white/[0.08] rounded-full font-medium transition-colors text-white">
              View Pricing
            </a>
          </div>

        </motion.div>
      </section>

      {/* 2. REAL LOOKUP EXAMPLES */}
      <section className="py-24 px-6 max-w-7xl mx-auto z-10 relative border-t border-white/5 bg-gradient-to-b from-transparent to-black/50">
        <div className="mb-16 md:flex justify-between items-end">
          <div className="max-w-2xl">
            <h2 className="text-3xl md:text-4xl font-bold mb-4 text-white tracking-tight">Live Intelligence Vectors</h2>
            <p className="text-gray-400">Sample sanitized payloads generated by our backend cleaner. Instant resolution across multiple data nodes.</p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <SampleCard icon={<User />} title="Number Lookup" subtitle="Telecom carrier & circle tracing" data={[{ label: 'Carrier', value: 'Jio Telecom' }, { label: 'Circle', value: 'Maharashtra' }, { label: 'Risk', value: 'Clean' }]} />
          <SampleCard icon={<Car />} title="Vehicle Lookup" subtitle="RC records & vehicle specs" data={[{ label: 'Reg No', value: 'MH-12-AB-****' }, { label: 'Model', value: 'Honda City 2023' }, { label: 'Status', value: 'Active' }]} />
          <SampleCard icon={<CreditCard />} title="UPI Intelligence" subtitle="Virtual Payment Address validation" data={[{ label: 'VPA', value: 'user@upi' }, { label: 'Bank', value: 'HDFC Bank Ltd' }, { label: 'Status', value: 'Valid' }]} />
          <SampleCard icon={<ShieldCheck />} title="Aadhaar Verification" subtitle="Demographic validation flags" data={[{ label: 'Status', value: 'Verified Record' }, { label: 'ID', value: '[Redacted]' }, { label: 'State', value: 'West Bengal' }]} />
          <SampleCard icon={<Globe />} title="Domain Lookup" subtitle="DNS & registrar intelligence" data={[{ label: 'Registrar', value: 'Namecheap Inc' }, { label: 'Creation', value: '2021-04-12' }, { label: 'Risk', value: 'Low' }]} />
          <SampleCard icon={<Shield />} title="Scam Detection" subtitle="Threat feed cross-referencing" data={[{ label: 'Database', value: 'National Scam Index' }, { label: 'Reports', value: '0 Complaints' }, { label: 'Verified', value: 'MoonWitch' }]} />
        </div>
      </section>

      {/* 3. USE CASES & BENEFITS */}
      <section className="py-24 px-6 max-w-7xl mx-auto z-10 relative">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold mb-4 text-white tracking-tight">Enterprise Capabilities</h2>
          <p className="text-gray-400 max-w-2xl mx-auto">Designed for threat analysts, independent researchers, and security teams.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <BenefitBox title="Scam Identification" desc="Identify suspicious numbers and VPAs before transferring funds." />
          <BenefitBox title="Vehicle Verification" desc="Verify ownership and registration specs for peer-to-peer purchases." />
          <BenefitBox title="Identity Validation" desc="Confirm identity parameters against databases to prevent fraud." />
          <BenefitBox title="Cyber Awareness" desc="Research publicly exposed risk footprints to audit personal exposure." />
        </div>
      </section>

      {/* 4. PRICING SECTION */}
      <section id="pricing" className="py-24 px-6 max-w-7xl mx-auto z-10 relative border-t border-pink-900/40 bg-black/60 backdrop-blur-md">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold mb-4 text-white tracking-tight">Transparent Pricing</h2>
          <p className="text-gray-400">Scale your operations with flexible access tiers.</p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 items-stretch">
          <PricingCard title="Pay As You Go" price="₹50" period="25 Credits" desc="Minimum buy 20 credits." features={['Full API access', 'Lifetime validity', 'JSON Export']} />
          <PricingCard title="Weekly Pro" price="₹499" period="7 Days" desc="Unlimited short investigations." popular features={['Unlimited lookups', 'Bypass credit logic', 'Premium badge']} />
          <PricingCard title="Monthly Elite" price="₹1,499" period="30 Days" desc="Enterprise access for analysts." features={['Unlimited volume', 'Advanced queues', 'Threat feeds']} />
          <PricingCard title="Lifetime Pass" price="₹9,999" period="Forever" desc="Permanent platform access." features={['Permanent access', 'Zero recurring sub', 'VIP nodes']} />
        </div>
      </section>

      <Footer />
    </div>
  );
}

// --- REUSABLE COMPONENTS ---

function FloatingPetals() {
  const [petals, setPetals] = useState<any[]>([]);

  useEffect(() => {
    // Increased to 50 petals with highly saturated colors
    const vibrantColors = ['#ec4899', '#e11d48', '#be123c', '#fb7185'];
    
    const newPetals = Array.from({ length: 50 }).map((_, i) => ({
      id: i,
      left: Math.random() * 100, 
      duration: Math.random() * 12 + 8, // Slightly faster falling (8 to 20 seconds)
      delay: Math.random() * 10, 
      size: Math.random() * 14 + 10, // Larger size (10px to 24px)
      color: vibrantColors[Math.floor(Math.random() * vibrantColors.length)], 
    }));
    setPetals(newPetals);
  }, []);

  return (
    <div className="absolute inset-0 overflow-hidden pointer-events-none z-0">
      {petals.map((petal) => (
        <motion.div
          key={petal.id}
          className="absolute top-[-5%]"
          style={{ left: `${petal.left}%` }}
          initial={{ y: -50, rotate: 0, opacity: 0 }}
          animate={{
            y: ['0vh', '110vh'],
            x: [0, Math.random() * 150 - 75, Math.random() * 150 - 75], // Wider horizontal drift
            rotate: [0, 360, 720], // Continuous spinning
            opacity: [0, 1, 1, 0], // Reaches full opacity
          }}
          transition={{
            duration: petal.duration,
            delay: petal.delay,
            repeat: Infinity,
            ease: "linear",
          }}
        >
          {/* Petal SVG with intense glowing drop-shadow */}
          <svg width={petal.size} height={petal.size} viewBox="0 0 24 24" fill={petal.color} className="opacity-90 drop-shadow-[0_0_8px_rgba(236,72,153,0.8)]">
            <path d="M12 2C6.48 2 2 6.48 2 12C2 17.52 6.48 22 12 22C17.52 22 22 17.52 22 12C22 6.48 17.52 2 12 2ZM12 20C7.59 20 4 16.41 4 12C4 7.59 7.59 4 12 4C16.41 4 20 7.59 20 12C20 16.41 16.41 20 12 20Z" opacity="0" />
            <path d="M12 2.25C8.5 2.25 2 6 2 12C2 17 8.5 21.75 12 21.75C15.5 21.75 22 17 22 12C22 6 15.5 2.25 12 2.25Z" />
          </svg>
        </motion.div>
      ))}
    </div>
  );
}

function TypewriterEffect({ words }: { words: string[] }) {
  const [currentWordIndex, setCurrentWordIndex] = useState(0);
  const [currentText, setCurrentText] = useState('');
  const [isDeleting, setIsDeleting] = useState(false);

  useEffect(() => {
    const word = words[currentWordIndex];
    const typeSpeed = isDeleting ? 30 : 80;
    
    const timeout = setTimeout(() => {
      if (!isDeleting && currentText === word) {
        setTimeout(() => setIsDeleting(true), 2500); 
      } else if (isDeleting && currentText === '') {
        setIsDeleting(false);
        setCurrentWordIndex((prev) => (prev + 1) % words.length);
      } else {
        setCurrentText(word.substring(0, currentText.length + (isDeleting ? -1 : 1)));
      }
    }, typeSpeed);

    return () => clearTimeout(timeout);
  }, [currentText, isDeleting, currentWordIndex, words]);

  return (
    <span className="inline-block relative">
      <span className="text-transparent bg-clip-text bg-gradient-to-br from-white via-gray-200 to-pink-500 drop-shadow-[0_0_15px_rgba(236,72,153,0.3)]">
        {currentText}
      </span>
      <span className="text-pink-500 animate-pulse ml-1 font-light">|</span>
    </span>
  );
}

function SampleCard({ icon, title, subtitle, data }: { icon: React.ReactNode; title: string; subtitle: string; data: { label: string; value: string }[] }) {
  return (
    <div className="bg-[#050304]/80 backdrop-blur-md border border-white/10 p-6 rounded-2xl hover:border-pink-500/40 transition-all duration-300 group relative overflow-hidden shadow-lg">
      <div className="absolute top-0 right-0 w-32 h-32 bg-pink-500/0 group-hover:bg-pink-500/15 blur-[40px] transition-colors" />
      <div className="flex items-center gap-4 mb-6 relative z-10">
        <div className="text-gray-400 group-hover:text-pink-400 transition-colors">{icon}</div>
        <div>
          <h3 className="text-sm font-semibold text-white">{title}</h3>
          <p className="text-xs text-gray-500">{subtitle}</p>
        </div>
      </div>
      <div className="space-y-1 font-mono text-xs relative z-10">
        {data.map((item, i) => (
          <div key={i} className="flex justify-between items-center py-2 border-b border-white/5 last:border-0">
            <span className="text-gray-500">{item.label}</span>
            <span className="text-pink-100 font-medium">{item.value}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

function BenefitBox({ title, desc }: { title: string; desc: string }) {
  return (
    <div className="bg-[#050304]/80 backdrop-blur-md border border-white/10 p-6 rounded-2xl hover:border-pink-500/40 transition-colors group shadow-lg">
      <div className="mb-4 text-gray-500 group-hover:text-pink-400 transition-colors">
        <Check className="w-5 h-5" />
      </div>
      <h3 className="text-base font-semibold text-white mb-2">{title}</h3>
      <p className="text-sm text-gray-400 leading-relaxed">{desc}</p>
    </div>
  );
}

function PricingCard({ title, price, period, desc, features, popular }: { title: string; price: string; period: string; desc: string; features: string[]; popular?: boolean }) {
  return (
    <div className={`bg-[#050304]/90 backdrop-blur-xl border transition-all duration-300 min-h-[460px] flex flex-col justify-between ${popular ? 'border-pink-500/70 shadow-[0_0_40px_rgba(236,72,153,0.2)] relative z-10' : 'border-white/10 hover:border-pink-500/40'} p-8 rounded-3xl relative overflow-hidden`}>
      {popular && <div className="absolute top-0 inset-x-0 h-1 bg-gradient-to-r from-pink-500 to-rose-500" />}
      <div className="flex-1">
        <div className="flex justify-between items-start mb-2">
          <h3 className="text-lg font-semibold text-white">{title}</h3>
          {popular && <span className="bg-pink-500/20 text-pink-400 text-[10px] px-2 py-1 rounded-full uppercase tracking-widest font-bold border border-pink-500/30">Popular</span>}
        </div>
        <p className="text-xs text-gray-500 mb-6">{desc}</p>
        <div className="text-4xl font-bold text-white mb-1 tracking-tight drop-shadow-md">{price} <span className="text-sm font-normal text-gray-500 tracking-normal">/ {period}</span></div>
        <div className="space-y-4 mt-8 pt-6 border-t border-white/5">
          {features.map((f, i) => (
            <div key={i} className="flex items-start gap-3 text-sm text-gray-400">
              <Check className="w-4 h-4 text-pink-500 shrink-0" />
              <span>{f}</span>
            </div>
          ))}
        </div>
      </div>
      <Link to="/login" className={`mt-8 w-full py-3 rounded-xl font-medium text-sm text-center transition-all duration-300 ${popular ? 'bg-gradient-to-r from-pink-600 to-rose-600 hover:from-pink-500 hover:to-rose-500 text-white shadow-[0_0_20px_rgba(236,72,153,0.4)]' : 'bg-white/5 border border-white/10 hover:bg-white/10 text-white'}`}>
        Choose Plan
      </Link>
    </div>
  );
}
