import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { 
  Shield, Zap, ArrowRight, Check, Activity, 
  Globe, User, Car, CreditCard, ShieldCheck, 
  LayoutDashboard, Smartphone, Key, Crosshair
} from 'lucide-react';
import { Link } from 'react-router-dom';
import Navbar from '../components/layout/Navbar';
import Footer from '../components/layout/Footer';

export default function Landing() {
  return (
    <div className="min-h-screen bg-black text-gray-200 selection:bg-pink-500/30 selection:text-white relative overflow-hidden font-sans">
      
      {/* --- 3D RADIATING BEAMS BACKGROUND --- */}
      <RadiatingBeams />

      <Navbar />

      {/* 1. HERO SECTION */}
      <section className="relative pt-40 pb-24 px-6 max-w-7xl mx-auto text-center flex flex-col items-center z-10">
        <motion.div 
          initial={{ opacity: 0, y: 30 }} 
          animate={{ opacity: 1, y: 0 }} 
          transition={{ duration: 0.8, ease: "easeOut" }} 
          className="w-full"
        >
          
          <div className="mx-auto w-fit px-5 py-2 rounded-full border border-white/10 bg-white/[0.02] backdrop-blur-xl text-gray-300 text-xs font-semibold tracking-wide mb-8 flex items-center gap-3 shadow-[inset_0_1px_1px_rgba(255,255,255,0.1)]">
            <span className="relative flex h-2.5 w-2.5">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-pink-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2.5 w-2.5 bg-pink-500"></span>
            </span>
            MoonWitch OSINT Engine v4.2
          </div>
          
          <h1 className="text-5xl md:text-7xl font-extrabold tracking-tighter mb-6 max-w-5xl mx-auto leading-[1.05] text-white drop-shadow-2xl">
            Intelligence <br />
            <TypewriterEffect words={['Beyond Search.', 'In Real-Time.', 'Without Limits.', 'At Scale.']} />
          </h1>
          
          <p className="text-gray-400 text-lg md:text-xl max-w-2xl mx-auto mb-10 leading-relaxed font-light">
            An enterprise-grade intelligence platform. Recover information from public databases instantly, verify identities, and evaluate risk footprints securely.
          </p>
          
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 relative z-20">
            <Link to="/login" className="px-8 py-4 bg-white text-black hover:bg-gray-100 rounded-full font-bold inline-flex items-center gap-2 transition-all shadow-[0_0_30px_rgba(255,255,255,0.2)] hover:shadow-[0_0_40px_rgba(236,72,153,0.4)] hover:scale-105">
              Start Analysis <ArrowRight className="w-5 h-5" />
            </Link>

            <Link to="/dashboard" className="px-8 py-4 bg-pink-600/20 border border-pink-500/40 hover:bg-pink-600/30 text-pink-300 rounded-full font-bold inline-flex items-center gap-2 transition-all shadow-[0_0_20px_rgba(236,72,153,0.2)] hover:scale-105 backdrop-blur-md">
              <LayoutDashboard className="w-5 h-5 text-pink-400" /> Dashboard
            </Link>

            <a href="#pricing" className="px-8 py-4 bg-white/[0.03] backdrop-blur-md border border-white/10 hover:border-white/20 hover:bg-white/[0.08] rounded-full font-semibold transition-all text-white shadow-[inset_0_1px_1px_rgba(255,255,255,0.05)]">
              View Pricing
            </a>
          </div>

        </motion.div>
      </section>

      {/* 2. REAL LOOKUP EXAMPLES (JSON SCHEMA FORMAT) */}
      <section className="py-24 px-6 max-w-7xl mx-auto z-10 relative">
        <motion.div 
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-50px" }}
          transition={{ duration: 0.6 }}
          className="mb-16 md:flex justify-between items-end"
        >
          <div className="max-w-2xl">
            <h2 className="text-4xl md:text-5xl font-bold mb-4 text-white tracking-tight">Live Intelligence Vectors</h2>
            <p className="text-gray-400 font-light text-lg">Raw JSON schemas generated by our backend. 5 key modules optimized for instant resolution.</p>
          </div>
        </motion.div>

        {/* Updated gap: wider horizontally (gap-x-6) but much tighter vertically (gap-y-3) */}
        <div className="flex flex-wrap justify-center gap-x-6 gap-y-3 max-w-7xl mx-auto">
          <SampleCard 
            index={0} 
            icon={<Smartphone />} 
            title="Number Lookup" 
            subtitle="Telecom & Demographics Extraction" 
            jsonString={`{\n  "mobile": "",\n  "name": "",\n  "address": "",\n  "circle": "",\n  "alt": "",\n  "fname": "",\n  "aadhaar": "",\n  "email": "",\n  "truecaller_name": ""\n}`}
          />
          <SampleCard 
            index={1} 
            icon={<ShieldCheck />} 
            title="Aadhaar Intelligence" 
            subtitle="Identity Extraction" 
            jsonString={`{\n  "mobile": "",\n  "name": "",\n  "father_name": "",\n  "address": "",\n  "alternate": "",\n  "circle": "",\n  "aadhar": "",\n  "email": ""\n}`}
          />
          <SampleCard 
            index={2} 
            icon={<Car />} 
            title="Vehicle Lookup" 
            subtitle="RTO & Ownership Details Extraction" 
            jsonString={`{\n  "address": {\n    "city": "",\n    "permanent": "",\n    "pincode": "",\n    "present": ""\n  },\n  "": "",\n  "": {\n    "name": ""\n  },\n  "owner": {\n    "father_name": "",\n    "name": ""\n  },\n  "puc": {\n    "no": "",\n    "valid_upto": ""\n  },\n  "registration": {\n    "authority": "",\n    "date": "",\n    "rto": "",\n    "rto_code": ""\n  },\n  "registration_number": "",\n  "response_time": 4.78,\n  "rto_contact": {\n    "phone": "(+91)"\n  },\n  "success": true,\n  "vehicle": {\n    "cc": ,\n    "class": "",\n    "commercial": ,\n    "fuel": "",\n    "fuel_norms": "",\n    "maker_model": "",\n    "manufacturer": "",\n    "model": "",\n    "seating": ,\n    "type": "",\n    "variant": ""\n  },\n  "insurance": {\n    "company": "",\n    "expired": ,\n    "policy_no": "",\n    "valid_upto": ""\n  }\n}`}
          />
          <SampleCard 
            index={3} 
            icon={<Key />} 
            title="Vehicle to Number" 
            subtitle="Contact Number Extraction" 
            jsonString={`{\n  "vehicle": "",\n  "chassis_number": "",\n  "engine_number": "",\n  "mobile_number": ""\n}`}
          />
          <SampleCard 
            index={4} 
            icon={<Crosshair />} 
            title="Bomber Module" 
            subtitle="Automated Sms Spammer " 
            jsonString={`{\n  "rounds": ,\n  "target": ""\n}`}
          />
        </div>
      </section>

      {/* 3. CAPABILITIES / BENEFITS SECTION */}
      <section className="py-24 px-6 max-w-7xl mx-auto z-10 relative">
        <motion.div 
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-50px" }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl md:text-5xl font-bold mb-4 text-white tracking-tight">Investigation Capabilities</h2>
          <p className="text-gray-400 max-w-2xl mx-auto font-light text-lg">Designed for investigators, cybersecurity professionals, journalists, threat analysts, and security teams.</p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <BenefitBox index={0} title="Scam Identification" desc="Analyze phone numbers, payment IDs, and digital footprints to identify potential fraud before engaging." />
          <BenefitBox index={1} title="Threat Intelligence" desc="Correlate publicly available information to uncover infrastructure, aliases, and online activity." />
          <BenefitBox index={2} title="Digital Investigations" desc="Accelerate investigations by connecting identities, vehicles, contact details, and public records." />
          <BenefitBox index={3} title="Risk Assessment" desc="Evaluate individuals, businesses, and online entities using publicly available intelligence sources." />
        </div>
      </section>

      {/* 4. 4-TIER PRICING SECTION */}
      <section id="pricing" className="py-32 px-6 max-w-7xl mx-auto z-10 relative">
        <motion.div 
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-50px" }}
          transition={{ duration: 0.6 }}
          className="text-center mb-20"
        >
          <h2 className="text-5xl md:text-6xl font-bold mb-6 text-white tracking-tighter">Transparent Pricing</h2>
          <p className="text-gray-400 text-lg font-light">Scale your operations with flexible access tiers.</p>
        </motion.div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 items-stretch">
          <PricingCard 
            index={0}
            title="Pay As You Go" 
            price="₹50" 
            period="25 Credits" 
            desc="Minimum buy 20 credits." 
            features={['Full API access', 'Lifetime credit validity', 'JSON Export capabilities']} 
          />
          <PricingCard 
            index={1}
            title="Weekly Pro" 
            price="₹499" 
            period="7 Days" 
            desc="Unlimited short investigations." 
            popular 
            features={['Unlimited lookups', 'Bypass credit logic', 'Priority premium badge']} 
          />
          <PricingCard 
            index={2}
            title="Monthly Elite" 
            price="₹1,499" 
            period="30 Days" 
            desc="Enterprise access for analysts." 
            features={['Unlimited query volume', 'Advanced server queues', 'Live threat data feeds']} 
          />
          <PricingCard 
            index={3}
            title="Lifetime Pass" 
            price="₹9,999" 
            period="Forever" 
            desc="Permanent platform access." 
            features={['Permanent access', 'Zero recurring sub', 'VIP priority nodes']} 
          />
        </div>
      </section>

      <Footer />
    </div>
  );
}

// --- REUSABLE COMPONENTS ---

function RadiatingBeams() {
  const BEAM_COUNT = 24;
  
  return (
    <div className="absolute inset-0 overflow-hidden z-0 pointer-events-none mix-blend-screen bg-black">
      <motion.div 
        animate={{ rotate: 360 }}
        transition={{ duration: 150, repeat: Infinity, ease: "linear" }}
        className="absolute inset-0 flex items-center justify-center"
      >
        {Array.from({ length: BEAM_COUNT }).map((_, i) => (
          <div
            key={i}
            className="absolute origin-left"
            style={{
              width: '150vmax',
              height: '40px',
              left: '50%',
              top: '50%',
              rotate: `${(360 / BEAM_COUNT) * i}deg`,
              background: 'linear-gradient(to bottom, #000 0%, #000 35%, rgba(236,72,153,0.6) 48%, #fff 50%, rgba(236,72,153,0.3) 52%, #000 65%, #000 100%)',
              opacity: 0.8,
            }}
          />
        ))}
      </motion.div>
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_50%,#000_5%,transparent_30%,#000_80%)]" />
      <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 mix-blend-overlay" />
    </div>
  );
}

function TypewriterEffect({ words }: { words: string[] }) {
  const [currentWordIndex, setCurrentWordIndex] = useState(0);
  const [currentText, setCurrentText] = useState('');
  const [isDeleting, setIsDeleting] = useState(false);

  useEffect(() => {
    const word = words[currentWordIndex];
    const typeSpeed = isDeleting ? 30 : 90;
    
    const timeout = setTimeout(() => {
      if (!isDeleting && currentText === word) {
        setTimeout(() => setIsDeleting(true), 3000); 
      } else if (isDeleting && currentText === '') {
        setIsDeleting(false);
        setCurrentWordIndex((prev) => (prev + 1) % words.length);
      } else {
        setCurrentText(word.substring(0, currentText.length + (isDeleting ? -1 : 1)));
      }
    }, typeSpeed);

    return () => clearTimeout(timeout);
  }, [currentText, isDeleting, currentWordIndex, words]);

  return (
    <span className="inline-block relative">
      <span className="text-transparent bg-clip-text bg-gradient-to-b from-white to-gray-400 drop-shadow-lg">
        {currentText}
      </span>
      <span className="text-pink-500 animate-[pulse_1s_ease-in-out_infinite] ml-2 font-light">|</span>
    </span>
  );
}

// Reusable Sample Card Block
function SampleCard({ icon, title, subtitle, jsonString, index }: { icon: React.ReactNode; title: string; subtitle: string; jsonString: string; index: number }) {
  return (
    <motion.div 
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-50px" }}
      transition={{ duration: 0.5, delay: index * 0.1 }}
      className="w-full md:w-[calc(50%-0.75rem)] lg:w-[calc(33.333%-1rem)] min-h-[380px] bg-black/40 backdrop-blur-2xl border border-white/[0.08] shadow-[inset_0_1px_1px_rgba(255,255,255,0.2),0_8px_32px_rgba(0,0,0,0.8)] p-6 rounded-[2rem] hover:bg-white/[0.02] transition-all duration-500 group relative overflow-hidden flex flex-col"
    >
      <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-30 mix-blend-overlay pointer-events-none" />
      
      <div className="flex items-center gap-4 mb-5 relative z-10">
        <div className="p-3 bg-white/[0.05] rounded-2xl text-gray-300 group-hover:text-pink-400 group-hover:bg-pink-500/10 transition-colors shadow-inner">
          {icon}
        </div>
        <div>
          <h3 className="text-base font-bold text-white tracking-wide">{title}</h3>
          <p className="text-[11px] text-gray-400 font-light">{subtitle}</p>
        </div>
      </div>
      
      <div className="relative z-10 flex-1 flex flex-col justify-end">
        <div className="bg-black/60 border border-white/5 rounded-xl p-4 overflow-auto max-h-[180px] shadow-inner group-hover:border-pink-500/20 transition-colors scrollbar-thin scrollbar-thumb-pink-500/30 scrollbar-track-transparent">
          <pre className="text-[11px] md:text-xs font-mono text-pink-300 leading-relaxed drop-shadow-[0_0_8px_rgba(236,72,153,0.3)]">
            {jsonString}
          </pre>
        </div>
      </div>
    </motion.div>
  );
}

function BenefitBox({ title, desc, index }: { title: string; desc: string; index: number }) {
  return (
    <motion.div 
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-50px" }}
      transition={{ duration: 0.5, delay: index * 0.1 }}
      className="bg-black/40 backdrop-blur-2xl border border-white/[0.08] shadow-[inset_0_1px_1px_rgba(255,255,255,0.2)] p-6 rounded-[2rem] hover:bg-white/[0.02] transition-all duration-300 group relative overflow-hidden"
    >
      <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-30 mix-blend-overlay pointer-events-none" />
      
      <div className="relative z-10">
        <div className="mb-4 p-2.5 bg-white/5 w-fit rounded-xl text-gray-400 group-hover:text-pink-400 transition-colors">
          <Check className="w-5 h-5" />
        </div>
        <h3 className="text-base font-semibold text-white mb-2">{title}</h3>
        <p className="text-sm text-gray-400 leading-relaxed font-light">{desc}</p>
      </div>
    </motion.div>
  );
}

function PricingCard({ title, price, period, desc, features, popular, index }: { title: string; price: string; period: string; desc: string; features: string[]; popular?: boolean; index: number }) {
  return (
    <motion.div 
      initial={{ opacity: 0, y: 40 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-50px" }}
      transition={{ duration: 0.6, delay: index * 0.1 }}
      className={`bg-black/40 backdrop-blur-2xl transition-all duration-500 min-h-[480px] flex flex-col justify-between p-8 rounded-[2rem] relative group overflow-hidden ${popular ? 'border border-pink-500/50 shadow-[0_0_50px_rgba(236,72,153,0.15),inset_0_1px_1px_rgba(255,255,255,0.3)] z-10 scale-105' : 'border border-white/[0.08] shadow-[inset_0_1px_1px_rgba(255,255,255,0.2),0_8px_32px_rgba(0,0,0,0.8)] hover:bg-white/[0.04]'}`}
    >
      <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-30 mix-blend-overlay pointer-events-none" />

      {popular && (
        <span className="absolute top-4 right-6 bg-pink-500/20 text-pink-400 text-[10px] px-3 py-1 rounded-full uppercase tracking-widest font-bold border border-pink-500/30 z-10">
          Popular
        </span>
      )}

      <div className="flex-1 relative z-10">
        <h3 className="text-xl font-medium text-white tracking-tight mb-2">{title}</h3>
        <p className="text-xs text-gray-400 font-light leading-relaxed mb-6 pr-4">{desc}</p>
        
        <div className="text-4xl font-bold text-white mb-6 tracking-tighter">
          {price}<span className="text-sm font-normal text-gray-500 tracking-normal ml-1">/ {period}</span>
        </div>
        
        <div className="space-y-3 pt-4 border-t border-white/5">
          {features.map((f, i) => (
            <div key={i} className="flex items-start gap-3 text-xs text-gray-300 font-light">
              <div className="p-1 rounded-full bg-white/10 shrink-0 mt-0.5">
                <Check className="w-3 h-3 text-white" />
              </div>
              <span>{f}</span>
            </div>
          ))}
        </div>
      </div>

      <Link to="/login" className={`mt-8 w-full py-3.5 rounded-full font-semibold text-xs text-center transition-all duration-300 relative z-10 ${popular ? 'bg-white text-black hover:bg-gray-200 shadow-[0_0_20px_rgba(255,255,255,0.3)]' : 'bg-white/10 text-white hover:bg-white/20 shadow-[inset_0_1px_1px_rgba(255,255,255,0.1)]'}`}>
        Choose Plan
      </Link>
    </motion.div>
  );
}
